### ISSUE TITLE
doesnt work in m1 pro mac

### ISSUE THREAD

**Issue by markmark1** [gerdreiss/brewsage#6]
brewsage (master)$ ./start-cli.sh ;./start-tui.sh 
./start-cli.sh: line 1: 70190 Segmentation fault: 11  stack build --exec brewsage-exe
./start-tui.sh: line 1: 70192 Se

**Comment by tc-joegiralt** [comment]
same.

**Comment by gerdreiss** [comment]
Please check this:

https://github.com/commercialhaskell/stack/issues/5607

Hope it helps.
